name: coessing-2025
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - xarray
  - scipy
  - matplotlib
  - cartopy
  - gsw
  - geopandas
  - shapely
  - haversine
  - jupyterlab         
  - ipykernel          
  - pip 
  - fsspec
  - h5netcdf 
  - h5py               
  - requests 
  - aiohttp
  - ipywidgets

